### ISSUE TITLE
Visualisation carto non fonctionnelle

### ISSUE THREAD

**Issue by slafayIGN** [rok4/rok4.github.io#10]
Une erreur JS empêche la carte ici : https://rok4.github.io/#visualisation-du-quadrillage de s'afficher.

Des fichiers de config de https://github.com/IGNF/geoportal-configuration ne sont plus trouvés parce que la branche de travail semble avoir changé de nom.

```diff
- https://raw.githubusercontent.com/IGNF/geoportal-configuration/main/dist/decouverteConfig.json
+ https://raw.githubusercontent.com/IGNF/geoportal-configuration/new-url/dist/decouverteConfig.json

- https://raw.githubusercontent.com/IGNF/geoportal-configuration/main/dist/essentielsConfig.json
+ https://raw.githubusercontent.com/IGNF/geoportal-configuration/new-url/dist/essentielsConfig.json 
```

**Comment by Dolite** [comment]
C'est corrigé, merci pour la remontée.

**Comment by orosnel** [comment]
Bonjour,
Il semble que le problème se manifeste à nouveau
https://raw.githubusercontent.com/IGNF/geoportal-configuration/main/dist/essentielsConfig.json  en erreur
sur le repo
https://raw.githubusercontent.com/IGNF/geoportal-configuration/new-url/dist/essentielsConfig.json

**Comment by azarz** [comment]
Bonjour,

Il ne s'agit pas du même problème. En effet, toutes les urls en /main/ ne sont plus fonctionnelles depuis le 24 avril dernier. Voici pourquoi :
Les URLs en /main/ pointaient vers les fichiers configurés pour les flux "Géoportail", en wxs.ign.fr, flux dépréciés.
Les URLs en /new-url/ pointent quant à eux vers les flux à jour de la Géoplateforme.

Vous rencontrez cette erreur car vous utilisez une version non à jour des extensions Géoportail. Nous vous conseillons de mettre à jour ces extensions vers la dernière version : https://github.com/IGNF/geoportal-extensions/releases

**Comment by orosnel** [comment]
Merci pour votre réponse, la mise à jour du GpSDK2D a résolu le problème
